language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - "pip install nikola flake8 --use-mirrors"
  - "find plugins/*/ | grep 'requirements.txt' | xargs cat | xargs pip install && true"
script:
  - nosetests --with-doctest --doctest-options=+NORMALIZE_WHITESPACE
  - "flake8 --ignore=E501 ."
