language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
install:
  - "pip install -r requirements-full.txt --use-mirrors"
  - "pip install flake8 --use-mirrors"
  - "pip install freezegun --use-mirrors"
  - "pip install . --use-mirrors"
script:
  - nosetests --with-doctest --doctest-options=+NORMALIZE_WHITESPACE
  - "flake8 --ignore=E501 ."
