language: python
cache: apt
python:
  - "2.6"
  - "2.7"
  - "3.3"
matrix:
  include:
    - python: "2.7"
      env: NMODE=flake8
env:
    NMODE=nikola
install:
  - "if [[ $NMODE == 'nikola' ]]; then pip install nikola --use-mirrors; fi"
  - "if [[ $NMODE == 'nikola' ]]; then find plugins/*/ | grep 'requirements.txt' | xargs cat | xargs pip install && true; fi"
  - "if [[ $NMODE == 'flake8' ]]; then pip install flake8 --use-mirrors; fi"
script:
  - "if [[ $NMODE == 'nikola' ]]; then nosetests --with-doctest --doctest-options=+NORMALIZE_WHITESPACE --logging-filter=-yapsy; fi"
  - "if [[ $NMODE == 'flake8' ]]; then flake8 --ignore=E501 .; fi"
notifications:
  irc:
    channels:
      - "chat.freenode.net#nikola"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Change view: %{compare_url}"
      - "Build details: %{build_url}"
